source 'http://rubygems.org'
ruby '2.0.0'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'haml'

gem 'activerecord'
gem 'sinatra-activerecord'

gem 'rake'
gem 'rack-flash3', :git => "git://github.com/treeder/rack-flash.git"

gem 'bcrypt-ruby', '~> 3.0.0'

gem 'json'

gem "sinatra-cross_origin"

gem 'pg'